<a href="https://colab.research.google.com/github/xinxingwu-uk/Experiments_C_S/blob/main/Week3_Lesson2_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
df=pd.read_excel('/content/Test.xlsx',header=None)

In [5]:
df.shape

(10, 3)

In [6]:
df

0  1   2
0   1  2   3
1   4  3   1
2   2  6   7
3   1  2  10
4   9  0   1
5   3  4   6
6   1  2   3
7  11  2   3
8   4  5   8
9  21  7  90

In [7]:
from PIL import Image
import numpy as np

In [8]:
I = Image.open('/content/desktop.jpg')
I.show()
I_array = np.array(I)
print(I_array.shape)

(562, 700, 3)


In [9]:
I_array

array([[[ 72, 122, 235],
        [ 71, 120, 238],
        [ 70, 120, 241],
        ...,
        [219, 231, 245],
        [219, 231, 245],
        [219, 231, 245]],

       [[ 72, 123, 232],
        [ 71, 121, 234],
        [ 70, 121, 239],
        ...,
        [219, 231, 245],
        [219, 231, 245],
        [219, 231, 245]],

       [[ 72, 121, 223],
        [ 71, 122, 227],
        [ 71, 123, 235],
        ...,
        [218, 230, 244],
        [218, 230, 244],
        [218, 230, 244]],

       ...,

       [[ 40,  64,   4],
        [ 40,  64,   4],
        [ 34,  58,   0],
        ...,
        [ 45,  65,  12],
        [ 43,  63,  12],
        [ 39,  62,  10]],

       [[ 53,  70,  15],
        [ 52,  69,  14],
        [ 50,  67,  12],
        ...,
        [ 39,  59,   8],
        [ 37,  57,   6],
        [ 35,  55,   4]],

       [[ 53,  70,  15],
        [ 52,  69,  14],
        [ 50,  67,  12],
        ...,
        [ 39,  59,   8],
        [ 37,  57,   6],
        [ 35,  55,   4]]

In [10]:
I = Image.open('/content/img_1.jpg')
I.show()
I_array = np.array(I)
print(I_array.shape)

(28, 28)


In [11]:
print(I_array)

[[  0   0   0   0   0   0   0   0   0   1   3   0   0   4   2   0  11   0
    0  14   1   0  19   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  12   0   0   7   0   1  10   0   2
    2  16   0   3   3   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   7   8   0   8   0   0   8   0   0  19
    0   0   1  21   0   4   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   1   0   0   1   0   0   0   0
    0  11   0   0  10   3   0   0   0   0]
 [  0   0   0   0   0   0   0   0  13   0  15  10  26  34  17  77 181 178
   35   4   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 150 254 250 251 243 252 252 255
   45   6   0   5   0   9   0   0   0   0]
 [  0   0   0   0   0   0   0   0   7  72 205 255 238 243 255 254 251 248
  201 198  57   0  19   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 218 255 241 255 249 250 251 250 255
  255 242 224  49   0  12   0   0   0   0]
 [  0   0   1   2   3   2   2   1   0  65 228 255 254 244 119  3

In [14]:
print(I_array//200)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 